import Groq from "groq-sdk"

const groq = new Groq({
  apiKey: process.env.GROG_API_KEY!,
})

export async function generateSummary(
  text: string,
  maxLength: number = 300
): Promise<string> {
  try {
    console.log("🚀 Generating summary with Groq (FREE!)")
    console.log("Input text length:", text.length, "characters")

    const maxInputLength = 30000 // Changed from 100000
    const truncatedText = text.length > maxInputLength 
      ? text.substring(0, maxInputLength) + "...\n\n[Note: Text was truncated due to length]" 
      : text

    console.log("Text length after truncation:", truncatedText.length, "characters")
    console.log("Estimated tokens:", Math.ceil(truncatedText.length / 4))

    const prompt = `You are a professional summarizer. Please provide a clear, concise summary of the following text in approximately ${maxLength} words. Focus on the main points, key ideas, and important details.

Text to summarize:
${truncatedText}

Summary:`

    console.log("Sending request to Groq (Llama 3.1)...")

    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile", 
      messages: [
        {
          role: "system",
          content: "You are a professional summarizer. Provide clear, concise summaries that capture the main points and key ideas. Be thorough but concise."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      temperature: 0.5,
      max_tokens: 600, 
      top_p: 1,
      stream: false,
    })

    const summary = completion.choices[0]?.message?.content

    if (!summary) {
      throw new Error("No summary generated by Groq")
    }

    console.log("✅ Summary generated successfully!")
    console.log("Summary length:", summary.length, "characters")
    console.log("Model used:", completion.model)

    return summary.trim()

  } catch (error) {
    console.error("❌ Groq summarization error:", error)
    
    const err = error as { status?: number } & Error
    
    if (err.status === 401) {
      throw new Error("Invalid Groq API key. Check your GROQ_API_KEY in .env")
    }
    
    if (err.status === 429) {
      throw new Error("Groq rate limit exceeded. Wait a minute and try again.")
    }

    throw new Error(`Failed to generate summary: ${err.message}`)
  }
}