import OpenAI from "openai";

const openai = new OpenAI({
    apiKey : process.env.OPENAI_API_KEY!,
})

export async function generateSummary(
     text: string,
     maxLength : number = 300
){
    try {
        console.log("Generating summary for the text of length" , text.length , "characters");

        const maxInput = 100000
        const truncatedText = text.length > maxInput
        ? text.substring(0 , maxInput) + "..." : text
        
        console.log("Length after truncation:" , truncatedText.length);

         const prompt = `You are a professional summarizer. Please provide a clear, concise summary of the following text in approximately ${maxLength} words. Focus on the main points, key ideas, and important details.

Text to summarize:
${truncatedText}

Summary:`

    console.log("Sending request to GPT-4...");

  const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: "You are a professional summarizer. Provide clear, concise summaries that capture the main points and key ideas."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      temperature: 0.5, 
      max_tokens: 500,
    })

    const summary = completion.choices[0]?.message?.content
    if(!summary){
        throw new Error("No summary generated by AI")
    }

    console.log("Summary Generated Successfully");
    console.log("Summary Length:" , summary.length , "characters");

    return summary.trim();
        
    } catch (error) {
        console.log("AI summarization Error" , error);
        throw new Error(`Failed to generate summary: ${(error as Error).message}`)
        
        
    }
   
    
}